### ISSUE TITLE
@FXML not working on Controller

### ISSUE THREAD

**Issue by viniciusccarvalho** [gluonhq/ignite#18]
I started using the micronaut integration today, and it was a very nice welcome to see support on javafx.

I hit an issue though, my controller is not getting the components from the view injected via @FXML

```
@Singleton
public class MainViewController {

    @Client("https://dog.ceo/api")
    @Inject
    RxHttpClient httpClient;

    @FXML
    ImageView imageView;

    public void call(ActionEvent event) {
        httpClient.retrieve(HttpRequest.GET("/breeds/image/random"), DogResponse.class)
        .subscribe(dogResponse -> updateImageView(dogResponse.getMessage()));
    }

    @OnFXThread
    void updateImageView(String href){
        this.imageView.setImage(new Image(href));
    }

}
```

The imageView is always null. The bind works from the fxml to the action on the controller, but not the FXML.

I'm new to javaFX, and after reading about it, seems that I would need a module-info.java to allow FXMLoader to inject the value.

Problem is that micronaut 2.x has an issue with java-modules : https://github.com/micronaut-projects/micronaut-core/issues/5095 , they seem to have fixed it on 3.x 

I can always make a contribution to upgrade the ignite-micronaut to 3.x branch and see if that helps, but wanted to see if I'm missing something obvious here.

Cheers

**Comment by viniciusccarvalho** [comment]
ahh never mind, I had a typo on `fx:id` :P

**Comment by eugener** [comment]
One small comment if you will.. 
Having an annotation on the controller class (like `@Singleton` in your case) does not make much sense as controller is created by JavaFX FXML engine instead of Microunaut. Ignite makes sure that controller class is injectable anyway.
We are always open for contributions!

**Comment by viniciusccarvalho** [comment]
Thank you @eugener I've updated my code with your suggestions :)

**Comment by viniciusccarvalho** [comment]
@eugener I hope you don't mind if I pick your brain on this one. I've changed my code to wrap the imageView on a StackPane, and I'm having NPEs again:

```
public class MainViewController {

    @Client("https://dog.ceo/api")
    @Inject
    RxHttpClient httpClient;

    @FXML
   StackPane imageFrame;

    public void call(ActionEvent event) {
        httpClient.retrieve(HttpRequest.GET("/breeds/image/random"), DogResponse.class)
                .subscribe(dogResponse -> updateImageView(dogResponse.getMessage()));
    }
    @OnFXThread
    void updateImageView(String href){
        if(this.imageFrame != null) {
            Image image = new Image(href);
            ImageView imageView = new ImageView(image);
            imageView.setPreserveRatio(true);
            imageFrame.getChildren().clear();
            imageFrame.getChildren().add(imageView);
            StackPane.setAlignment(imageView, Pos.CENTER);
        }
    }
}
```
and my fxml:

```
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.control.*?>
<?import javafx.scene.layout.*?>
<?import javafx.scene.text.*?>

<AnchorPane prefHeight="400.0" prefWidth="600.0" xmlns="http://javafx.com/javafx/11.0.2" xmlns:fx="http://javafx.com/fxml/1" fx:controller="io.igx.fx.views.main.MainViewController">
   <children>
      <Button fx:id="fetchBtn" layoutX="200.0" layoutY="341.0" mnemonicParsing="false" onAction="#call" prefHeight="27.0" prefWidth="200.0" text="Fetch" textFill="WHITE">
         <font>
            <Font name="Courier New Bold" size="24.0" />
         </font>
      </Button>
      <StackPane id="imageFrame" layoutX="51.0" layoutY="32.0" prefHeight="274.0" prefWidth="499.0" />
   </children>
</AnchorPane>
```

When I had a imageView component and the button only on my fxml I was able to get the pointer to the imageView, but now the pane is null. What is strange is that the style present on `MainView.css` does get applied to the component:

```
#fetchBtn {
    -fx-background-color: #0b7306;
    -fx-background-radius: 30;
}
#imageFrame {
    -fx-background-color: #000000;
    -fx-border-color: #b07c4a;
    -fx-border-style: solid;
    -fx-border-width: 5;
}
```

Any pointers? I'm more than happy to share this little project as a sample if you will, there are a few nuances that took me a few tries to get right and a sample may help others.

Cheers and thank you for this :) I'm actually enjoying client development again :)

**Comment by eugener** [comment]
The question to ask here if when are you calling `updateImageView` method? 
Here is  the lifecycle of FXML Controller:
1. It's constructor is called first
2.  `ignite` is finally able to let Micronaut inject other dependencies
3. `@FXML` fields are injected
4. `initalize` method is called 
Keeping this in mind will allow you to avoid premature use of injectable values.

**Comment by viniciusccarvalho** [comment]
Another silly mistake, the id was set as `id` not `fx:id` although I swear I did it via scene builder.

The `updateImage` is called after everything is created, it reacts to an event to the button. After fixing the NPE, I got 
`Caused by: java.lang.IllegalStateException: Not on FX application thread; currentThread = default-nioEventLoopGroup-1-1`

Funny cause the last time this was working fine and the method is annotated with `@OnFXThread` it is invoke from a non `FXThread` but I was hoping there's thread context switching here.

Almost here :D 

Thanks for all the input

**Comment by eugener** [comment]
There should be unless we have a bug... current implementation of `FXThreadInterseptor` ensures that we run on FX Thread:
``` java
@Singleton
class OnFXThreadInterceptor implements MethodInterceptor<Object, Object> {
    @Override
    public Object intercept(MethodInvocationContext<Object, Object> context) {
        if ( !Platform.isFxApplicationThread() ) {
            Platform.runLater(context::proceed);
            return null;
        }
        return context.proceed();
    }
}
```
But... I don't think I've ever tested that on Micronaut 3

**Comment by viniciusccarvalho** [comment]
I'm running on 2 still, I noted that the interceptor is not being invoked in my code. The controller is not declared as a `@Singleton` and I thought that was a requirement for the interceptors to be applied.

**Comment by eugener** [comment]
And... I would suggest not do any styling within FMXL beyond setting style classes.
it makes styling changes very inconvenient

**Comment by eugener** [comment]
re: interceptors...  you're correct here. My first suggestion was out of line actually :)
Looking at the code I realized, that we do get controller as a bean:
``` java
@Factory
public class FXMLLoaderFactory {

    @Inject private ApplicationContext ctx;

    @Prototype
    public FXMLLoader getLoader() {
        FXMLLoader loader = new FXMLLoader();
        loader.setControllerFactory(ctx::getBean);
        return loader;
    }

}
```
So the `@Singleton` is actually needed here

**Comment by viniciusccarvalho** [comment]
I'm still getting the error, even after adding the `@Singleton`, what I'm confused about is how this worked before :) 

From my call stack I can see the intercepted proxy seems to be invoked:

```
at io.igx.fx.views.main.$MainViewControllerDefinition$Intercepted.$$access$$updateImageView(Unknown Source)
```

But the methodInterceptor is never invoked (at least not from a debug point)

Now, I think (I need to double check this) that even micronaut (I'm sure about spring) you can't call a proxied method from a method on the same type, the proxy does not apply to it.
