### ISSUE TITLE
Ignite Micronaut Examples

### ISSUE THREAD

**Issue by kinsleykajiva** [gluonhq/ignite#22]
hi, i have been looking around for DI frameworks or libs to use for java fx, but now I have taken interest in this, seems like there are no extensive examples on Ignite Micronaut for me to be sure that its what I am looking for in particular. I intend to build a big complex desktop application, that will have a lot of HTTP requests and use Real-time protocols like WebSockets plus other defined protocols.

Can you please assist and give some pointers of some sort.

**Comment by eugener** [comment]
Ignite Micronaut implementation covers main pain points which people usually face with combining reflection based approach used in JavaFX with DI approach used by Microanut. It also makes few annoying things easier. All of those features are described in [Micronaut Support](https://github.com/gluonhq/ignite#micronaut-support) section of `Readme.md`. 

Please let us know if you have any questions or suggestions
