### ISSUE TITLE
Update Gluon Ignite Webpage

### ISSUE THREAD

**Issue by AdamCarroll** [gluonhq/ignite#6]
The Gluon Ignite webpage has a link to a BitBucket repo that seems to no longer exist.  It looks like it should be updated to refer instead to this GitHub repo.  The page is here: https://gluonhq.com/labs/ignite/

**Comment by eugener** [comment]
Thank you very much for the suggestion! The page is updated.

**Comment by AdamCarroll** [comment]
Great! Thanks @eugener
