### ISSUE TITLE
POM of com.gluonhq:ignite-micronaut:jar:1.1.0 (in Maven Central) is invalid

### ISSUE THREAD

**Issue by fwscholz** [gluonhq/ignite#7]
Hello,

I try to use this artifact as dependency in a project's `pom.xml`.
Get the following warning and error message running Maven in 'debug mode' (`-X`).
```xml
[WARNING] The POM for com.gluonhq:ignite-micronaut:jar:1.1.0 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for com.gluonhq:ignite-micronaut:1.1.0
[ERROR] 'dependencies.dependency.version' for javax.annotation:javax.annotation-api:jar is missing. @
```

**Comment by eugener** [comment]
As a workaround, you can add it manually  
```
implementation("javax.annotation:javax.annotation-api")
```

**Comment by fwscholz** [comment]
Hello @eugener,

thanks for the quick response.

I'm not sure whether I get your proposed workaround right.
After adding _javax.annotation:javax.annotation-api:1.3.2_ as a dependency to my project's `pom.xml` I'm able to you use the annotations brought along by this artifact. But it seems I have to add all the dependencies declared in the invalid `pom.xml` of _com.gluonhq:ignite-micronaut:jar:1.1.0_ to work around the problem, cause of the invalidity there are no transitive dependencies available/resolved by Maven.

Regards,
Florian
